import type { Article } from "./types";

export const seedArticles: Article[] = [
  {
    id: "art-001",
    title: {
      fr: "Le président Tebboune préside le Conseil des ministres",
      ar: "الرئيس تبون يترأس مجلس الوزراء",
    },
    slug: {
      fr: "president-tebboune-conseil-ministres",
      ar: "tebboune-majlis-wuzara",
    },
    excerpt: {
      fr: "Le président de la République a présidé une réunion du Conseil des ministres consacrée aux réformes économiques et sociales.",
      ar: "ترأس رئيس الجمهورية اجتماعاً لمجلس الوزراء خُصص للإصلاحات الاقتصادية والاجتماعية.",
    },
    content: {
      fr: "Le président de la République, Abdelmadjid Tebboune, a présidé hier une réunion du Conseil des ministres axée sur les grandes réformes économiques et sociales en cours. Les membres du gouvernement ont passé en revue l'état d'avancement des différents chantiers ouverts, notamment ceux relatifs à la modernisation de l'administration publique et à l'amélioration du pouvoir d'achat des citoyens. Le président a insisté sur la nécessité d'accélérer le rythme des réformes et de garantir leur mise en œuvre effective sur le terrain.",
      ar: "ترأس رئيس الجمهورية عبد المجيد تبون أمس اجتماعاً لمجلس الوزراء تمحور حول الإصلاحات الاقتصادية والاجتماعية الكبرى الجارية. استعرض أعضاء الحكومة مدى التقدم المحرز في المشاريع المختلفة المفتوحة، لا سيما تلك المتعلقة بتحديث الإدارة العامة وتحسين القدرة الشرائية للمواطنين.",
    },
    category: "politique",
    source: "El Moudjahid",
    sourceUrl: "https://www.elmoudjahid.com",
    imageUrl: "https://picsum.photos/seed/art001/800/450",
    publishedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    lang: "fr",
    tags: ["politique", "gouvernement", "réformes"],
    curatedBy: "DzWire",
  },
  {
    id: "art-002",
    title: {
      fr: "Élections locales : la campagne bat son plein à Alger",
      ar: "الانتخابات المحلية: الحملة في أوجها بالجزائر العاصمة",
    },
    slug: {
      fr: "elections-locales-campagne-alger",
      ar: "intikhabat-mahalliya-hamla-algiers",
    },
    excerpt: {
      fr: "Les candidats aux élections locales intensifient leurs activités de campagne dans les quartiers populaires d'Alger.",
      ar: "يكثف المرشحون للانتخابات المحلية أنشطتهم الانتخابية في أحياء الجزائر الشعبية.",
    },
    content: {
      fr: "À quelques jours du scrutin, les candidats aux élections locales multiplient les réunions de proximité et les rencontres avec les habitants des différents quartiers de la capitale. Les thèmes dominants de la campagne restent l'amélioration des services publics, la gestion des déchets, l'entretien des routes et le développement des infrastructures sportives et culturelles.",
      ar: "قبل أيام قليلة من موعد الاقتراع، يكثر المرشحون للانتخابات المحلية من الاجتماعات الجوارية واللقاءات مع سكان مختلف أحياء العاصمة. وتبقى المواضيع المهيمنة على الحملة تحسين الخدمات العامة وتسيير النفايات وصيانة الطرق وتطوير البنية التحتية الرياضية والثقافية.",
    },
    category: "politique",
    source: "TSA Algérie",
    sourceUrl: "https://www.tsa-algerie.com",
    imageUrl: "https://picsum.photos/seed/art002/800/450",
    publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    lang: "fr",
    tags: ["élections", "politique", "Alger"],
    curatedBy: "DzWire",
  },
  {
    id: "art-003",
    title: {
      fr: "Diplomatie : l'Algérie accueille une conférence africaine",
      ar: "الدبلوماسية: الجزائر تستضيف مؤتمراً أفريقياً",
    },
    slug: {
      fr: "algerie-conference-africaine-diplomatie",
      ar: "algeria-mouatamar-afriqi-diblomasiya",
    },
    excerpt: {
      fr: "Alger accueille cette semaine une importante conférence panafricaine sur la sécurité et le développement.",
      ar: "تستضيف الجزائر هذا الأسبوع مؤتمراً أفريقياً هاماً حول الأمن والتنمية.",
    },
    content: {
      fr: "La capitale algérienne accueille une conférence panafricaine de haut niveau réunissant des délégués de plus de vingt pays africains. Les débats portent sur les défis sécuritaires au Sahel, les stratégies de développement économique durable et le renforcement de la coopération Sud-Sud. L'Algérie, qui joue un rôle de médiateur reconnu dans la région, a proposé plusieurs initiatives concrètes pour stabiliser les zones de tension.",
      ar: "تحتضن العاصمة الجزائرية مؤتمراً أفريقياً رفيع المستوى يجمع مندوبين من أكثر من عشرين دولة أفريقية. تدور النقاشات حول التحديات الأمنية في منطقة الساحل واستراتيجيات التنمية الاقتصادية المستدامة وتعزيز التعاون جنوب-جنوب.",
    },
    category: "politique",
    source: "El Watan",
    sourceUrl: "https://www.elwatan.com",
    imageUrl: "https://picsum.photos/seed/art003/800/450",
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    lang: "fr",
    tags: ["diplomatie", "Afrique", "sécurité"],
    curatedBy: "DzWire",
  },
  {
    id: "art-004",
    title: {
      fr: "Sonatrach signe un nouveau contrat d'exploration gazière",
      ar: "سوناطراك توقع عقداً جديداً للتنقيب عن الغاز",
    },
    slug: {
      fr: "sonatrach-contrat-exploration-gaz",
      ar: "sonatrach-aqd-jadid-tanqib-ghaz",
    },
    excerpt: {
      fr: "Le groupe pétrolier national Sonatrach annonce la signature d'un accord d'exploration avec un partenaire international.",
      ar: "تعلن مجموعة سوناطراك الوطنية للنفط عن توقيع اتفاقية استكشاف مع شريك دولي.",
    },
    content: {
      fr: "Sonatrach, le géant pétrolier algérien, a annoncé la signature d'un nouveau contrat d'exploration et d'exploitation gazière avec un consortium international. Cet accord couvre plusieurs blocs situés dans le bassin de Berkine, une région reconnue pour ses importantes réserves d'hydrocarbures. Les investissements prévus sur les cinq prochaines années s'élèvent à plusieurs milliards de dollars et devraient créer des milliers d'emplois directs et indirects.",
      ar: "أعلنت سوناطراك، عملاق النفط الجزائري، عن توقيع عقد جديد للتنقيب والاستغلال الغازي مع تحالف دولي. يغطي هذا الاتفاق عدة كتل تقع في حوض بركين، المنطقة المعروفة باحتياطياتها الكبيرة من المحروقات.",
    },
    category: "energie-economie",
    source: "Echorouk",
    sourceUrl: "https://www.echoroukonline.com",
    imageUrl: "https://picsum.photos/seed/art004/800/450",
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    lang: "ar",
    tags: ["Sonatrach", "gaz", "énergie", "investissement"],
    curatedBy: "DzWire",
  },
  {
    id: "art-005",
    title: {
      fr: "La Bourse d'Alger enregistre une hausse significative",
      ar: "بورصة الجزائر تسجل ارتفاعاً ملحوظاً",
    },
    slug: {
      fr: "bourse-alger-hausse-significative",
      ar: "borsa-alger-irtifaa-mulahaz",
    },
    excerpt: {
      fr: "Les indices boursiers algériens affichent une progression notable portée par les valeurs du secteur énergétique.",
      ar: "تُظهر المؤشرات البورصية الجزائرية تقدماً ملحوظاً مدفوعاً بقيم قطاع الطاقة.",
    },
    content: {
      fr: "La Bourse des valeurs mobilières d'Alger (COSOB) a clôturé la séance de jeudi sur une note positive, avec une hausse de 2,3% de l'indice général. Les valeurs du secteur énergétique ont mené la progression, soutenues par la remontée des cours mondiaux du pétrole. Les analystes attribuent également ce regain à de bons résultats trimestriels publiés par plusieurs sociétés cotées.",
      ar: "أغلقت بورصة القيم المنقولة بالجزائر (كوسوب) جلسة الخميس على نبرة إيجابية، مع ارتفاع المؤشر العام بنسبة 2.3٪. قادت قيم قطاع الطاقة التقدم، مدعومة بارتفاع أسعار النفط العالمية.",
    },
    category: "energie-economie",
    source: "Liberté Économique",
    sourceUrl: "https://www.liberte-algerie.com",
    imageUrl: "https://picsum.photos/seed/art005/800/450",
    publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    lang: "fr",
    tags: ["bourse", "économie", "finance"],
    curatedBy: "DzWire",
  },
  {
    id: "art-006",
    title: {
      fr: "Agriculture : le gouvernement lance un plan de modernisation",
      ar: "الزراعة: الحكومة تطلق مخططاً للتحديث",
    },
    slug: {
      fr: "agriculture-plan-modernisation-gouvernement",
      ar: "ziraa-makhtat-tahdith-houkoma",
    },
    excerpt: {
      fr: "Le ministère de l'Agriculture présente un plan ambitieux pour moderniser le secteur et réduire les importations alimentaires.",
      ar: "يقدم وزير الفلاحة مخططاً طموحاً لتحديث القطاع وتقليص الواردات الغذائية.",
    },
    content: {
      fr: "Le ministère de l'Agriculture a dévoilé un plan décennal visant à moderniser l'agriculture algérienne et à réduire la facture des importations alimentaires. Ce plan prévoit des investissements massifs dans l'irrigation goutte-à-goutte, la mécanisation des exploitations et la formation des agriculteurs aux nouvelles techniques culturales. L'objectif est d'atteindre l'autosuffisance dans plusieurs filières stratégiques d'ici à 2030.",
      ar: "كشفت وزارة الفلاحة عن مخطط عشري يهدف إلى تحديث الزراعة الجزائرية وتقليص فاتورة الواردات الغذائية. يتضمن هذا المخطط استثمارات ضخمة في الري بالتنقيط وميكنة المستثمرات وتكوين الفلاحين في التقنيات الزراعية الحديثة.",
    },
    category: "energie-economie",
    source: "El Khabar",
    sourceUrl: "https://www.elkhabar.com",
    imageUrl: "https://picsum.photos/seed/art006/800/450",
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    lang: "ar",
    tags: ["agriculture", "économie", "modernisation"],
    curatedBy: "DzWire",
  },
  {
    id: "art-007",
    title: {
      fr: "La startup algérienne Yassir lève 30 millions de dollars",
      ar: "الشركة الناشئة الجزائرية ياسير تجمع 30 مليون دولار",
    },
    slug: {
      fr: "yassir-startup-algerie-levee-fonds",
      ar: "yassir-startup-jazaer-taqdir-malioun",
    },
    excerpt: {
      fr: "La super-application algérienne Yassir annonce une nouvelle levée de fonds pour accélérer son expansion africaine.",
      ar: "تعلن التطبيق الجزائري الشامل ياسير عن جولة تمويل جديدة لتسريع توسعه الأفريقي.",
    },
    content: {
      fr: "Yassir, la super-application algérienne de transport, de livraison et de paiement mobile, vient d'annoncer une levée de fonds de 30 millions de dollars auprès d'investisseurs internationaux. Ces fonds seront utilisés pour renforcer la présence de l'entreprise en Afrique subsaharienne et pour développer de nouvelles fonctionnalités financières destinées aux populations non bancarisées.",
      ar: "أعلن ياسير، التطبيق الجزائري الشامل للنقل والتوصيل والدفع عبر الهاتف المحمول، عن جمع 30 مليون دولار من مستثمرين دوليين. ستُستخدم هذه الأموال لتعزيز حضور الشركة في أفريقيا جنوب الصحراء وتطوير ميزات مالية جديدة للسكان غير المصرفيين.",
    },
    category: "tech-innovation",
    source: "Startup Brics",
    sourceUrl: "https://startupbrics.com",
    imageUrl: "https://picsum.photos/seed/art007/800/450",
    publishedAt: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    lang: "fr",
    tags: ["startup", "tech", "fintech", "Yassir"],
    curatedBy: "DzWire",
  },
  {
    id: "art-008",
    title: {
      fr: "Algeria Tech Hub : le nouvel écosystème numérique d'Oran",
      ar: "مركز الجزائر للتكنولوجيا: النظام الرقمي الجديد في وهران",
    },
    slug: {
      fr: "algeria-tech-hub-oran-numerique",
      ar: "algeria-tech-hub-wahran-raqmi",
    },
    excerpt: {
      fr: "Oran se dote d'un pôle technologique moderne pour stimuler l'innovation et l'entrepreneuriat numérique dans l'ouest du pays.",
      ar: "تتزود وهران بقطب تكنولوجي حديث لتحفيز الابتكار وريادة الأعمال الرقمية في غرب البلاد.",
    },
    content: {
      fr: "Un nouveau pôle technologique vient d'ouvrir ses portes à Oran, dans le but de catalyser l'écosystème startup de l'Ouest algérien. Ce hub de 5 000 m² dispose d'espaces de coworking, de salles de conférence équipées, d'un fablab et d'un programme d'accélération pour les jeunes entrepreneurs. Soutenu par le ministère de l'Économie du savoir, il accueille déjà une vingtaine de startups prometteuses.",
      ar: "افتتح قطب تكنولوجي جديد أبوابه في وهران، بهدف تحفيز نظام الشركات الناشئة في غرب الجزائر. يضم هذا المركز البالغة مساحته 5000 متر مربع فضاءات للعمل المشترك وقاعات مؤتمرات مجهزة ومختبر تصنيع وبرنامج تسريع لرواد الأعمال الشباب.",
    },
    category: "tech-innovation",
    source: "Forbes Afrique",
    sourceUrl: "https://www.forbesafrique.com",
    imageUrl: "https://picsum.photos/seed/art008/800/450",
    publishedAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    lang: "fr",
    tags: ["tech", "startup", "Oran", "innovation"],
    curatedBy: "DzWire",
  },
  {
    id: "art-009",
    title: {
      fr: "Intelligence artificielle : l'Algérie forme ses premiers ingénieurs",
      ar: "الذكاء الاصطناعي: الجزائر تُخرّج أول دفعة من المهندسين",
    },
    slug: {
      fr: "intelligence-artificielle-algerie-formation-ingenieurs",
      ar: "dhaka-isnadi-jazaer-tadrif-muhandisin",
    },
    excerpt: {
      fr: "Une nouvelle promotion d'ingénieurs spécialisés en intelligence artificielle sort des universités algériennes.",
      ar: "تتخرج دفعة جديدة من المهندسين المتخصصين في الذكاء الاصطناعي من الجامعات الجزائرية.",
    },
    content: {
      fr: "L'Université des Sciences et de la Technologie Houari Boumediene (USTHB) a organisé la cérémonie de remise des diplômes à sa première promotion d'ingénieurs spécialisés en intelligence artificielle et apprentissage automatique. Ces 120 diplômés rejoignent un marché du travail en pleine transformation numérique, avec des opportunités dans les secteurs de la santé, de l'énergie, de l'agriculture et des services financiers.",
      ar: "نظمت جامعة العلوم والتكنولوجيا هواري بومدين حفل تخرج أول دفعة من المهندسين المتخصصين في الذكاء الاصطناعي والتعلم الآلي. ينضم هؤلاء الـ120 خريجاً إلى سوق عمل في خضم تحول رقمي، مع فرص في قطاعات الصحة والطاقة والزراعة والخدمات المالية.",
    },
    category: "tech-innovation",
    source: "Horizons",
    sourceUrl: "https://www.horizons-dz.com",
    imageUrl: "https://picsum.photos/seed/art009/800/450",
    publishedAt: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    lang: "fr",
    tags: ["IA", "technologie", "université", "formation"],
    curatedBy: "DzWire",
  },
  {
    id: "art-010",
    title: {
      fr: "Festival du film d'Oran : le palmarès dévoilé",
      ar: "مهرجان الفيلم في وهران: كشف النقاب عن قائمة الفائزين",
    },
    slug: {
      fr: "festival-film-oran-palmares",
      ar: "maharjan-film-wahran-qaemat-faizin",
    },
    excerpt: {
      fr: "Le Festival international du film arabe d'Oran a révélé ses lauréats lors d'une cérémonie haute en couleur.",
      ar: "كشف مهرجان الفيلم العربي الدولي بوهران عن الفائزين فيه خلال حفل بهيج.",
    },
    content: {
      fr: "La 20e édition du Festival international du film arabe d'Oran s'est clôturée samedi soir avec la remise des Wihr d'or. Le grand prix a été décerné au film algérien 'Mémoires d'une oasis', une fresque poétique sur la vie dans le Sahara. La cérémonie, retransmise sur la chaîne nationale, a rassemblé des cinéastes de quinze pays arabes et africains.",
      ar: "اختتمت الدورة العشرين لمهرجان الفيلم العربي الدولي بوهران مساء السبت بتسليم جوائز الوهر الذهبي. مُنحت الجائزة الكبرى للفيلم الجزائري 'ذكريات واحة'، وهي لوحة شعرية عن الحياة في الصحراء.",
    },
    category: "culture-gaming",
    source: "Le Soir d'Algérie",
    sourceUrl: "https://www.lesoirdalgerie.com",
    imageUrl: "https://picsum.photos/seed/art010/800/450",
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    lang: "fr",
    tags: ["cinéma", "festival", "Oran", "culture"],
    curatedBy: "DzWire",
  },
  {
    id: "art-011",
    title: {
      fr: "Les joueurs algériens brillent dans l'esport mondial",
      ar: "اللاعبون الجزائريون يتألقون في الرياضة الإلكترونية العالمية",
    },
    slug: {
      fr: "joueurs-algeriens-esport-mondial",
      ar: "laiboun-jazaerioun-riyada-ilktroniya-alamiya",
    },
    excerpt: {
      fr: "Plusieurs équipes algériennes se distinguent dans les compétitions internationales d'esport, portant haut les couleurs du pays.",
      ar: "تتألق فرق جزائرية عديدة في منافسات الرياضة الإلكترونية الدولية، رافعةً ألوان البلاد عالياً.",
    },
    content: {
      fr: "La scène esport algérienne connaît une véritable effervescence avec la montée en puissance de jeunes talents qui s'imposent sur la scène internationale. L'équipe nationale algérienne de Free Fire a décroché une médaille de bronze lors du championnat arabe, tandis que plusieurs gamers algériens ont rejoint des équipes professionnelles européennes et asiatiques. Le gouvernement envisage de créer une fédération nationale d'esport pour structurer et soutenir ce secteur en plein essor.",
      ar: "تشهد ساحة الرياضة الإلكترونية الجزائرية حراكاً حقيقياً مع صعود نجوم شباب يفرضون أنفسهم على الساحة الدولية. حصل المنتخب الجزائري لـ Free Fire على ميدالية برونزية في البطولة العربية، فيما انضم عدة لاعبين جزائريين إلى فرق احترافية أوروبية وآسيوية.",
    },
    category: "culture-gaming",
    source: "Tout sur l'Algérie",
    sourceUrl: "https://www.tsa-algerie.com",
    imageUrl: "https://picsum.photos/seed/art011/800/450",
    publishedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    lang: "fr",
    tags: ["esport", "gaming", "jeunesse", "culture"],
    curatedBy: "DzWire",
  },
  {
    id: "art-012",
    title: {
      fr: "TikTok Algérie : les créateurs locaux envahissent la plateforme",
      ar: "تيك توك الجزائر: المبدعون المحليون يغزون المنصة",
    },
    slug: {
      fr: "tiktok-algerie-createurs-locaux",
      ar: "tiktok-algiers-mubdioun-mahalioun",
    },
    excerpt: {
      fr: "Le contenu algérien sur TikTok explose, avec des créateurs qui cumulent des millions de vues grâce à l'humour et la culture locale.",
      ar: "ينفجر المحتوى الجزائري على تيك توك، مع مبدعين يجمعون ملايين المشاهدات بفضل الفكاهة والثقافة المحلية.",
    },
    content: {
      fr: "La communauté des créateurs de contenu algériens sur TikTok ne cesse de croître, avec plusieurs influenceurs qui ont franchi le cap du million d'abonnés. Ces jeunes Algériens capitalisent sur l'humour dialectal, la gastronomie, les paysages du pays et les défis culturels pour attirer une audience locale et diasporique. TikTok Algérie aurait récemment approché plusieurs créateurs pour des partenariats exclusifs.",
      ar: "يواصل مجتمع منشئي المحتوى الجزائريين على تيك توك نموه، مع عدة مؤثرين تجاوزوا حاجز المليون متابع. يوظف هؤلاء الشباب الجزائريون الفكاهة الدارجة والمطبخ والمناظر الطبيعية للبلاد والتحديات الثقافية لاستقطاب جمهور محلي وديناميكي.",
    },
    category: "medias-sociaux",
    source: "Algérie Focus",
    sourceUrl: "https://www.algeriefocus.com",
    imageUrl: "https://picsum.photos/seed/art012/800/450",
    publishedAt: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    lang: "fr",
    tags: ["TikTok", "réseaux sociaux", "contenu", "jeunesse"],
    curatedBy: "DzWire",
  },
  {
    id: "art-013",
    title: {
      fr: "Instagram en Algérie : le boom des influenceurs mode",
      ar: "إنستغرام في الجزائر: انتعاش المؤثرين في الموضة",
    },
    slug: {
      fr: "instagram-algerie-influenceurs-mode",
      ar: "instagram-algiers-muathirun-moda",
    },
    excerpt: {
      fr: "Les influenceurs mode algériens sur Instagram séduisent une audience internationale avec un style mêlant traditions et modernité.",
      ar: "يأسر مؤثرو الموضة الجزائريون على إنستغرام جمهوراً دولياً بأسلوب يمزج التقاليد والحداثة.",
    },
    content: {
      fr: "Le secteur de la mode algérienne connaît une révolution silencieuse portée par une nouvelle génération de créateurs et d'influenceurs sur Instagram. Ces passionnés de style fusionnent les motifs traditionnels kabyles et arabes avec les tendances mondiales pour créer une esthétique unique qui attire l'attention bien au-delà des frontières. Plusieurs marques européennes ont déjà approché ces influenceurs pour des collaborations.",
      ar: "يشهد قطاع الموضة الجزائرية ثورة صامتة تحملها جيل جديد من المصممين والمؤثرين على إنستغرام. يمزج هؤلاء المهتمون بالأناقة النقوش التقليدية القبائلية والعربية مع الاتجاهات العالمية لخلق جمالية فريدة تستقطب الانتباه.",
    },
    category: "medias-sociaux",
    source: "Algérie Mode",
    sourceUrl: "https://www.algerie-mode.com",
    imageUrl: "https://picsum.photos/seed/art013/800/450",
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    lang: "fr",
    tags: ["Instagram", "mode", "influenceurs", "social media"],
    curatedBy: "DzWire",
  },
  {
    id: "art-014",
    title: {
      fr: "CAN 2025 : la Fennec d'Algérie affûte ses armes",
      ar: "كأس الأمم الأفريقية 2025: الفنك الجزائري يُعدّ عدته",
    },
    slug: {
      fr: "can-2025-algerie-preparation",
      ar: "kan-2025-jazaer-tahdir",
    },
    excerpt: {
      fr: "La sélection nationale algérienne de football entame une phase de préparation intensive en vue de la prochaine Coupe d'Afrique des nations.",
      ar: "يشرع المنتخب الوطني الجزائري لكرة القدم في مرحلة تحضير مكثفة استعداداً لكأس الأمم الأفريقية القادمة.",
    },
    content: {
      fr: "L'équipe nationale algérienne de football a débuté un stage de préparation intensif au Centre technique national de Sidi Moussa. Le sélectionneur a convoqué 24 joueurs pour ce regroupement qui s'étalera sur deux semaines. Les séances d'entraînement sont axées sur l'amélioration du pressing, le travail offensif et la solidité défensive. Plusieurs matchs amicaux sont prévus contre des sélections africaines pour tester la forme du groupe.",
      ar: "شرع المنتخب الوطني الجزائري لكرة القدم في معسكر تحضيري مكثف بالمركز التقني الوطني بسيدي موسى. استدعى المدرب 24 لاعباً لهذا التجمع الذي سيمتد أسبوعين. تتمحور جلسات التدريب حول تحسين الضغط والعمل الهجومي والمتانة الدفاعية.",
    },
    category: "sport",
    source: "Le Buteur",
    sourceUrl: "https://www.lebuteur.com",
    imageUrl: "https://picsum.photos/seed/art014/800/450",
    publishedAt: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
    lang: "ar",
    tags: ["football", "CAN", "Algérie", "sport"],
    curatedBy: "DzWire",
  },
  {
    id: "art-015",
    title: {
      fr: "Ramiz Zerrouki, la révélation algérienne du football néerlandais",
      ar: "راميز زروقي، المفاجأة الجزائرية في كرة القدم الهولندية",
    },
    slug: {
      fr: "ramiz-zerrouki-football-neerlandais",
      ar: "ramiz-zerrouki-koura-qadam-hollandiya",
    },
    excerpt: {
      fr: "Le milieu de terrain algéro-néerlandais Ramiz Zerrouki confirme sa progression fulgurante dans l'élite européenne.",
      ar: "يؤكد لاعب الوسط الجزائري الهولندي راميز زروقي تقدمه المتسارع في النخبة الأوروبية.",
    },
    content: {
      fr: "Ramiz Zerrouki, le milieu de terrain algérien évoluant aux Pays-Bas, réalise une saison remarquable qui lui vaut les éloges de la presse européenne. Ses performances constantes et son intelligence de jeu ont attiré l'attention de plusieurs grands clubs. Le joueur, qui a effectué récemment sa première sélection avec l'équipe nationale algérienne, représente une nouvelle génération de bi-nationaux qui choisissent de défendre les couleurs de leurs racines.",
      ar: "يُجري راميز زروقي، لاعب الوسط الجزائري المحترف في هولندا، موسماً رائعاً يستحق به إشادة الصحافة الأوروبية. استقطبت أداءاته الثابتة وذكاؤه في اللعب انتباه عدة أندية كبرى. ويمثل اللاعب الذي أجرى مؤخراً استدعاءه الأول مع المنتخب الوطني الجزائري جيلاً جديداً من مزدوجي الجنسية الذين يختارون الدفاع عن ألوان جذورهم.",
    },
    category: "sport",
    source: "El Heddaf",
    sourceUrl: "https://www.elheddaf.com",
    imageUrl: "https://picsum.photos/seed/art015/800/450",
    publishedAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    lang: "ar",
    tags: ["football", "Zerrouki", "diaspora", "sport"],
    curatedBy: "DzWire",
  },
];
